services:
  - type: web
    name: presina-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --threads 100 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
